neo4j:
  name: my-standalone
  edition: "enterprise"    
  acceptLicenseAgreement: "yes"
  password: "password"         
  minimumClusterSize: 3        
  resources:
    cpu: "0.5"
    memory: "2Gi"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi

config:
  dbms.default_database: “neo4j”
  dbms.config.strict_validation: “true”

podSpec:
  podAntiAffinity: false
