apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    debug

    [INPUT]
        Name              tail
        Path              /logs/*.log
        Tag               neo4j.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Read_from_Head    On
        Skip_Long_Lines   On
        Path_Key          filename

    [OUTPUT]
        Name              loki
        Match             neo4j.*
        Host              loki.default.svc.cluster.local
        Port              3100
        Labels            job=neo4j,namespace=neo4j,file=$filename,pod=primary-0
        Line_Format       key_value
    
    [OUTPUT]
        Name              stdout
        Match             neo4j.*