# 0_prerequisites.yaml
---
# 1. Service Account (Workload Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j-gcs-sa
  namespace: application
  annotations:
    iam.gke.io/gcp-service-account: neo4j-gcs-gsa@chboudry-project.iam.gserviceaccount.com

---
# 2. Custom StorageClass for Neo4j data (SSD with Retain policy)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: neo4j-data-ssd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd  # Premium SSD
reclaimPolicy: Retain  # Keep data when PVC is deleted
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# 3. PV for data (pd-ssd)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: neo4j-data-ssd
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/chboudry-project/zones/europe-west1-b/disks/neo4j-data-disk
    fsType: ext4

---
# 4. PVC for data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: application
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: neo4j-data-ssd
  resources:
    requests:
      storage: 50Gi

---
# 5. StorageClass for import (GCS)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: neo4j-gcs-import
provisioner: gcsfuse.csi.storage.gke.io
parameters:
  bucketName: chboudry-import-bucket
volumeBindingMode: Immediate
allowVolumeExpansion: true

---
# 6. PV for import (GCS)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-import-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: neo4j-gcs-import
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: chboudry-import-bucket
    readOnly: false
    volumeAttributes:
      gcsfuseLoggingSeverity: warning

---
# 7. PVC for import
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-import-pvc
  namespace: application
  annotations:
    gke-gcsfuse/cpu-limit: "0"
    gke-gcsfuse/memory-limit: "0"
    gke-gcsfuse/ephemeral-storage-limit: "0"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: neo4j-gcs-import
  resources:
    requests:
      storage: 10Gi